<?php declare(strict_types=1);

namespace App\Database;

/**
 * Thin wrapper around mysqli used by the scaffold's ActiveRecord layer.
 */
class Database
{
    private ?\mysqli $connection;

    /**
     * Store the active mysqli connection.
     *
     * @param \mysqli $connection Open mysqli connection.
     */
    public function __construct(\mysqli $connection)
    {
        $this->connection = $connection;
    }

    /**
     * Execute a SQL query with optional mysqli native parameters.
     *
     * @param string $query SQL statement with `?` placeholders when needed.
     * @param array $params Values bound to the statement.
     * @return \mysqli_result|bool
     * @throws \RuntimeException When no database connection is available.
     */
    public function query(string $query, array $params = []): \mysqli_result|bool
    {
        if ($this->connection === null) {
            throw new \RuntimeException('No database connection set.');
        }

        return $this->connection->execute_query($query, $params);
    }

    /**
     * Return the ID generated by the latest insert query.
     *
     * @return int|string
     * @throws \RuntimeException When no database connection is available.
     */
    public function lastInsertId(): int|string
    {
        if ($this->connection === null) {
            throw new \RuntimeException('No database connection set.');
        }

        return $this->connection->insert_id;
    }

    /**
     * Close the mysqli connection if it is still open.
     *
     * @return void
     */
    public function close(): void
    {
        if ($this->connection !== null) {
            $this->connection->close();
            $this->connection = null;
        }
    }
}
